management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-nursery
    description: App about plants of the nursery.
    author: Jose Maria
    version: '@project.version@'

spring:
  profiles:
    active: dev

server:
  error:
    include-message: always
