server:
  port: 8090
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nursery
    username: josemaria
    password: maria17
    driver-class-name: org.postgresql.Driver
    #url: jdbc:h2:file:./src/main/resources/db/nursery;AUTO_SERVER=TRUE
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true