server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/nursery
#    username: josemaria
#    password: maria17
#    driver-class-name: org.postgresql.Driver
#    #url: jdbc:h2:file:./src/main/resources/db/nursery;AUTO_SERVER=TRUE
#  jpa:
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true