package org.fdryt.ornamental.dto;

public enum Family {

    EUPHORBIACEAE, FABACEAE, ASPARAGACEAE, SOLANACEAE,
    LAMIACEAE, SALICACEAE, ASPHODELACEAE, AMARYLLIDACEAE,
    COMMELINACEAE, ARACEAE, RUSCACEAE, BEGONIACEAE,
    VERBENACEAE, APOCYNACEAE, MALVACEAE, BROMELIACEAE,
    NYCTAGINACEAE, CACTACEAE, RUBIACEAE, MARANTACEAE,
    SAPINDACEAE, ARALIACEAE, ANNONACEAE, RUTACEAE,
    VITACEAE, POLYPODIACEAE, CRASSULACEAE, ROSACEAE,
    MYRTACEAE, MORACEAE, OLEACEAE, ONAGRACEAE, GESNERIACEAE,
    XANTHORRHOEACEAE, ASPLENIACEAE, DAVALLICEAE,
    AMARANTHACEAE, BIGNONIACEAE, AGAVACEAE, PASIFLORACEAE,
    ANACARDIACEAE, PHYTOKACCACEAE, PORTULACACEAE, LAURACEAE,
    CARICACEAE, CYPERACEAE, GERANIACEAE, CUPRESSACEAE,
    PINACEAE, URTICACEAE, ASTERACEAE, SAXIFRAGACEAE,
    MIMOSACEAE, BALSAMINACEAE, PASSIFLORACEAE, ACANTHACEAE
}
